on:
  push:
    branches:
      - master
  pull_request:

name: Run gallery code

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC",
            os: ubuntu-latest
          }
        - {
            name: "macOS Latest Clang",
            os: macos-latest
          }

    steps:
    - uses: actions/checkout@v4

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Configure the build
      run: cmake -S . -B build

    - name: Run the build
      run: cmake --build build

    - name: Run the no-argument tests
      if: ${{ matrix.config.os == 'ubuntu-latest' }}
      run: | 
        cd build/
        for x in $(find . -maxdepth 1 -type f -executable)
        do
            echo "#### RUNNING ${x} ####"
            echo
            ./${x}
            echo
        done

    - name: Run the no-argument tests
      if: ${{ matrix.config.os == 'macos-latest' }}
      run: | 
        cd build/
        for x in $(find . -maxdepth 1 -type f -perm +0111)
        do
            echo "#### RUNNING ${x} ####"
            echo
            ./${x}
            echo
        done
